# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import integrity_pb2 as integrity__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in integrity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntegrityServiceStub(object):
    """IntegrityService defines the gRPC service for integrity operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformIntegrityCheck = channel.unary_unary(
                '/gpushield.integrity.v1.IntegrityService/PerformIntegrityCheck',
                request_serializer=integrity__pb2.IntegrityCheckRequest.SerializeToString,
                response_deserializer=integrity__pb2.IntegrityReport.FromString,
                _registered_method=True)
        self.StreamIntegrityReports = channel.stream_stream(
                '/gpushield.integrity.v1.IntegrityService/StreamIntegrityReports',
                request_serializer=integrity__pb2.IntegrityReport.SerializeToString,
                response_deserializer=integrity__pb2.IntegrityResponse.FromString,
                _registered_method=True)
        self.GetIntegrityStatus = channel.unary_unary(
                '/gpushield.integrity.v1.IntegrityService/GetIntegrityStatus',
                request_serializer=integrity__pb2.GetIntegrityStatusRequest.SerializeToString,
                response_deserializer=integrity__pb2.IntegrityStatusResponse.FromString,
                _registered_method=True)
        self.UpdateTrustedBaseline = channel.unary_unary(
                '/gpushield.integrity.v1.IntegrityService/UpdateTrustedBaseline',
                request_serializer=integrity__pb2.UpdateTrustedBaselineRequest.SerializeToString,
                response_deserializer=integrity__pb2.UpdateTrustedBaselineResponse.FromString,
                _registered_method=True)


class IntegrityServiceServicer(object):
    """IntegrityService defines the gRPC service for integrity operations
    """

    def PerformIntegrityCheck(self, request, context):
        """Perform integrity check on a node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIntegrityReports(self, request_iterator, context):
        """Stream integrity reports
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntegrityStatus(self, request, context):
        """Get integrity status for a node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTrustedBaseline(self, request, context):
        """Update trusted baselines
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntegrityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformIntegrityCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformIntegrityCheck,
                    request_deserializer=integrity__pb2.IntegrityCheckRequest.FromString,
                    response_serializer=integrity__pb2.IntegrityReport.SerializeToString,
            ),
            'StreamIntegrityReports': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamIntegrityReports,
                    request_deserializer=integrity__pb2.IntegrityReport.FromString,
                    response_serializer=integrity__pb2.IntegrityResponse.SerializeToString,
            ),
            'GetIntegrityStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegrityStatus,
                    request_deserializer=integrity__pb2.GetIntegrityStatusRequest.FromString,
                    response_serializer=integrity__pb2.IntegrityStatusResponse.SerializeToString,
            ),
            'UpdateTrustedBaseline': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTrustedBaseline,
                    request_deserializer=integrity__pb2.UpdateTrustedBaselineRequest.FromString,
                    response_serializer=integrity__pb2.UpdateTrustedBaselineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gpushield.integrity.v1.IntegrityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gpushield.integrity.v1.IntegrityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntegrityService(object):
    """IntegrityService defines the gRPC service for integrity operations
    """

    @staticmethod
    def PerformIntegrityCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpushield.integrity.v1.IntegrityService/PerformIntegrityCheck',
            integrity__pb2.IntegrityCheckRequest.SerializeToString,
            integrity__pb2.IntegrityReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamIntegrityReports(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gpushield.integrity.v1.IntegrityService/StreamIntegrityReports',
            integrity__pb2.IntegrityReport.SerializeToString,
            integrity__pb2.IntegrityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntegrityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpushield.integrity.v1.IntegrityService/GetIntegrityStatus',
            integrity__pb2.GetIntegrityStatusRequest.SerializeToString,
            integrity__pb2.IntegrityStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTrustedBaseline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpushield.integrity.v1.IntegrityService/UpdateTrustedBaseline',
            integrity__pb2.UpdateTrustedBaselineRequest.SerializeToString,
            integrity__pb2.UpdateTrustedBaselineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
