# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryServiceStub(object):
    """TelemetryService defines the gRPC service for telemetry data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_stream(
                '/gpushield.telemetry.v1.TelemetryService/StreamTelemetry',
                request_serializer=telemetry__pb2.TelemetryData.SerializeToString,
                response_deserializer=telemetry__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.GetNodeMetrics = channel.unary_unary(
                '/gpushield.telemetry.v1.TelemetryService/GetNodeMetrics',
                request_serializer=telemetry__pb2.GetNodeMetricsRequest.SerializeToString,
                response_deserializer=telemetry__pb2.TelemetryData.FromString,
                _registered_method=True)
        self.GetHistoricalMetrics = channel.unary_stream(
                '/gpushield.telemetry.v1.TelemetryService/GetHistoricalMetrics',
                request_serializer=telemetry__pb2.GetHistoricalMetricsRequest.SerializeToString,
                response_deserializer=telemetry__pb2.TelemetryData.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """TelemetryService defines the gRPC service for telemetry data
    """

    def StreamTelemetry(self, request_iterator, context):
        """Stream telemetry data from sensors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeMetrics(self, request, context):
        """Get current metrics for a specific node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalMetrics(self, request, context):
        """Get historical metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=telemetry__pb2.TelemetryData.FromString,
                    response_serializer=telemetry__pb2.TelemetryResponse.SerializeToString,
            ),
            'GetNodeMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeMetrics,
                    request_deserializer=telemetry__pb2.GetNodeMetricsRequest.FromString,
                    response_serializer=telemetry__pb2.TelemetryData.SerializeToString,
            ),
            'GetHistoricalMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHistoricalMetrics,
                    request_deserializer=telemetry__pb2.GetHistoricalMetricsRequest.FromString,
                    response_serializer=telemetry__pb2.TelemetryData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gpushield.telemetry.v1.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gpushield.telemetry.v1.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """TelemetryService defines the gRPC service for telemetry data
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gpushield.telemetry.v1.TelemetryService/StreamTelemetry',
            telemetry__pb2.TelemetryData.SerializeToString,
            telemetry__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpushield.telemetry.v1.TelemetryService/GetNodeMetrics',
            telemetry__pb2.GetNodeMetricsRequest.SerializeToString,
            telemetry__pb2.TelemetryData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricalMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gpushield.telemetry.v1.TelemetryService/GetHistoricalMetrics',
            telemetry__pb2.GetHistoricalMetricsRequest.SerializeToString,
            telemetry__pb2.TelemetryData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
