// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: integrity.proto

package integrity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IntegrityStatus represents the overall integrity state
type IntegrityStatus int32

const (
	IntegrityStatus_INTEGRITY_STATUS_UNKNOWN     IntegrityStatus = 0
	IntegrityStatus_INTEGRITY_STATUS_TRUSTED     IntegrityStatus = 1
	IntegrityStatus_INTEGRITY_STATUS_COMPROMISED IntegrityStatus = 2
	IntegrityStatus_INTEGRITY_STATUS_SUSPICIOUS  IntegrityStatus = 3
	IntegrityStatus_INTEGRITY_STATUS_ERROR       IntegrityStatus = 4
)

// Enum value maps for IntegrityStatus.
var (
	IntegrityStatus_name = map[int32]string{
		0: "INTEGRITY_STATUS_UNKNOWN",
		1: "INTEGRITY_STATUS_TRUSTED",
		2: "INTEGRITY_STATUS_COMPROMISED",
		3: "INTEGRITY_STATUS_SUSPICIOUS",
		4: "INTEGRITY_STATUS_ERROR",
	}
	IntegrityStatus_value = map[string]int32{
		"INTEGRITY_STATUS_UNKNOWN":     0,
		"INTEGRITY_STATUS_TRUSTED":     1,
		"INTEGRITY_STATUS_COMPROMISED": 2,
		"INTEGRITY_STATUS_SUSPICIOUS":  3,
		"INTEGRITY_STATUS_ERROR":       4,
	}
)

func (x IntegrityStatus) Enum() *IntegrityStatus {
	p := new(IntegrityStatus)
	*p = x
	return p
}

func (x IntegrityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_integrity_proto_enumTypes[0].Descriptor()
}

func (IntegrityStatus) Type() protoreflect.EnumType {
	return &file_integrity_proto_enumTypes[0]
}

func (x IntegrityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrityStatus.Descriptor instead.
func (IntegrityStatus) EnumDescriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{0}
}

// ComponentType categorizes different types of components
type ComponentType int32

const (
	ComponentType_COMPONENT_TYPE_UNKNOWN       ComponentType = 0
	ComponentType_COMPONENT_TYPE_DRIVER        ComponentType = 1
	ComponentType_COMPONENT_TYPE_FIRMWARE      ComponentType = 2
	ComponentType_COMPONENT_TYPE_KERNEL_MODULE ComponentType = 3
	ComponentType_COMPONENT_TYPE_LIBRARY       ComponentType = 4
	ComponentType_COMPONENT_TYPE_APPLICATION   ComponentType = 5
	ComponentType_COMPONENT_TYPE_CONFIGURATION ComponentType = 6
)

// Enum value maps for ComponentType.
var (
	ComponentType_name = map[int32]string{
		0: "COMPONENT_TYPE_UNKNOWN",
		1: "COMPONENT_TYPE_DRIVER",
		2: "COMPONENT_TYPE_FIRMWARE",
		3: "COMPONENT_TYPE_KERNEL_MODULE",
		4: "COMPONENT_TYPE_LIBRARY",
		5: "COMPONENT_TYPE_APPLICATION",
		6: "COMPONENT_TYPE_CONFIGURATION",
	}
	ComponentType_value = map[string]int32{
		"COMPONENT_TYPE_UNKNOWN":       0,
		"COMPONENT_TYPE_DRIVER":        1,
		"COMPONENT_TYPE_FIRMWARE":      2,
		"COMPONENT_TYPE_KERNEL_MODULE": 3,
		"COMPONENT_TYPE_LIBRARY":       4,
		"COMPONENT_TYPE_APPLICATION":   5,
		"COMPONENT_TYPE_CONFIGURATION": 6,
	}
)

func (x ComponentType) Enum() *ComponentType {
	p := new(ComponentType)
	*p = x
	return p
}

func (x ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_integrity_proto_enumTypes[1].Descriptor()
}

func (ComponentType) Type() protoreflect.EnumType {
	return &file_integrity_proto_enumTypes[1]
}

func (x ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentType.Descriptor instead.
func (ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{1}
}

// SecurityEventType categorizes security events
type SecurityEventType int32

const (
	SecurityEventType_SECURITY_EVENT_TYPE_UNKNOWN              SecurityEventType = 0
	SecurityEventType_SECURITY_EVENT_TYPE_INTEGRITY_VIOLATION  SecurityEventType = 1
	SecurityEventType_SECURITY_EVENT_TYPE_UNAUTHORIZED_ACCESS  SecurityEventType = 2
	SecurityEventType_SECURITY_EVENT_TYPE_MALWARE_DETECTION    SecurityEventType = 3
	SecurityEventType_SECURITY_EVENT_TYPE_ANOMALOUS_BEHAVIOR   SecurityEventType = 4
	SecurityEventType_SECURITY_EVENT_TYPE_CONFIGURATION_CHANGE SecurityEventType = 5
	SecurityEventType_SECURITY_EVENT_TYPE_PRIVILEGE_ESCALATION SecurityEventType = 6
	SecurityEventType_SECURITY_EVENT_TYPE_DATA_EXFILTRATION    SecurityEventType = 7
)

// Enum value maps for SecurityEventType.
var (
	SecurityEventType_name = map[int32]string{
		0: "SECURITY_EVENT_TYPE_UNKNOWN",
		1: "SECURITY_EVENT_TYPE_INTEGRITY_VIOLATION",
		2: "SECURITY_EVENT_TYPE_UNAUTHORIZED_ACCESS",
		3: "SECURITY_EVENT_TYPE_MALWARE_DETECTION",
		4: "SECURITY_EVENT_TYPE_ANOMALOUS_BEHAVIOR",
		5: "SECURITY_EVENT_TYPE_CONFIGURATION_CHANGE",
		6: "SECURITY_EVENT_TYPE_PRIVILEGE_ESCALATION",
		7: "SECURITY_EVENT_TYPE_DATA_EXFILTRATION",
	}
	SecurityEventType_value = map[string]int32{
		"SECURITY_EVENT_TYPE_UNKNOWN":              0,
		"SECURITY_EVENT_TYPE_INTEGRITY_VIOLATION":  1,
		"SECURITY_EVENT_TYPE_UNAUTHORIZED_ACCESS":  2,
		"SECURITY_EVENT_TYPE_MALWARE_DETECTION":    3,
		"SECURITY_EVENT_TYPE_ANOMALOUS_BEHAVIOR":   4,
		"SECURITY_EVENT_TYPE_CONFIGURATION_CHANGE": 5,
		"SECURITY_EVENT_TYPE_PRIVILEGE_ESCALATION": 6,
		"SECURITY_EVENT_TYPE_DATA_EXFILTRATION":    7,
	}
)

func (x SecurityEventType) Enum() *SecurityEventType {
	p := new(SecurityEventType)
	*p = x
	return p
}

func (x SecurityEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_integrity_proto_enumTypes[2].Descriptor()
}

func (SecurityEventType) Type() protoreflect.EnumType {
	return &file_integrity_proto_enumTypes[2]
}

func (x SecurityEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityEventType.Descriptor instead.
func (SecurityEventType) EnumDescriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{2}
}

// SecurityEventSeverity represents the severity of a security event
type SecurityEventSeverity int32

const (
	SecurityEventSeverity_SECURITY_EVENT_SEVERITY_UNKNOWN  SecurityEventSeverity = 0
	SecurityEventSeverity_SECURITY_EVENT_SEVERITY_INFO     SecurityEventSeverity = 1
	SecurityEventSeverity_SECURITY_EVENT_SEVERITY_LOW      SecurityEventSeverity = 2
	SecurityEventSeverity_SECURITY_EVENT_SEVERITY_MEDIUM   SecurityEventSeverity = 3
	SecurityEventSeverity_SECURITY_EVENT_SEVERITY_HIGH     SecurityEventSeverity = 4
	SecurityEventSeverity_SECURITY_EVENT_SEVERITY_CRITICAL SecurityEventSeverity = 5
)

// Enum value maps for SecurityEventSeverity.
var (
	SecurityEventSeverity_name = map[int32]string{
		0: "SECURITY_EVENT_SEVERITY_UNKNOWN",
		1: "SECURITY_EVENT_SEVERITY_INFO",
		2: "SECURITY_EVENT_SEVERITY_LOW",
		3: "SECURITY_EVENT_SEVERITY_MEDIUM",
		4: "SECURITY_EVENT_SEVERITY_HIGH",
		5: "SECURITY_EVENT_SEVERITY_CRITICAL",
	}
	SecurityEventSeverity_value = map[string]int32{
		"SECURITY_EVENT_SEVERITY_UNKNOWN":  0,
		"SECURITY_EVENT_SEVERITY_INFO":     1,
		"SECURITY_EVENT_SEVERITY_LOW":      2,
		"SECURITY_EVENT_SEVERITY_MEDIUM":   3,
		"SECURITY_EVENT_SEVERITY_HIGH":     4,
		"SECURITY_EVENT_SEVERITY_CRITICAL": 5,
	}
)

func (x SecurityEventSeverity) Enum() *SecurityEventSeverity {
	p := new(SecurityEventSeverity)
	*p = x
	return p
}

func (x SecurityEventSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecurityEventSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_integrity_proto_enumTypes[3].Descriptor()
}

func (SecurityEventSeverity) Type() protoreflect.EnumType {
	return &file_integrity_proto_enumTypes[3]
}

func (x SecurityEventSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecurityEventSeverity.Descriptor instead.
func (SecurityEventSeverity) EnumDescriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{3}
}

// IntegrityReport represents a comprehensive integrity assessment
type IntegrityReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeId    string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname  string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ReportId  string                 `protobuf:"bytes,4,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	// Overall integrity status
	OverallStatus IntegrityStatus `protobuf:"varint,5,opt,name=overall_status,json=overallStatus,proto3,enum=gpushield.integrity.v1.IntegrityStatus" json:"overall_status,omitempty"`
	// Component-specific integrity checks
	Components []*ComponentIntegrity `protobuf:"bytes,6,rep,name=components,proto3" json:"components,omitempty"`
	// Attestation data
	Attestation *AttestationData `protobuf:"bytes,7,opt,name=attestation,proto3" json:"attestation,omitempty"`
	// Security events
	SecurityEvents []*SecurityEvent `protobuf:"bytes,8,rep,name=security_events,json=securityEvents,proto3" json:"security_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IntegrityReport) Reset() {
	*x = IntegrityReport{}
	mi := &file_integrity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityReport) ProtoMessage() {}

func (x *IntegrityReport) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityReport.ProtoReflect.Descriptor instead.
func (*IntegrityReport) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{0}
}

func (x *IntegrityReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IntegrityReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *IntegrityReport) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *IntegrityReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *IntegrityReport) GetOverallStatus() IntegrityStatus {
	if x != nil {
		return x.OverallStatus
	}
	return IntegrityStatus_INTEGRITY_STATUS_UNKNOWN
}

func (x *IntegrityReport) GetComponents() []*ComponentIntegrity {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *IntegrityReport) GetAttestation() *AttestationData {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *IntegrityReport) GetSecurityEvents() []*SecurityEvent {
	if x != nil {
		return x.SecurityEvents
	}
	return nil
}

// ComponentIntegrity represents integrity data for a specific component
type ComponentIntegrity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ComponentName    string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"` // "nvidia_driver", "cuda_runtime", "kernel_module", etc.
	ComponentVersion string                 `protobuf:"bytes,2,opt,name=component_version,json=componentVersion,proto3" json:"component_version,omitempty"`
	ComponentType    ComponentType          `protobuf:"varint,3,opt,name=component_type,json=componentType,proto3,enum=gpushield.integrity.v1.ComponentType" json:"component_type,omitempty"`
	Status           IntegrityStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=gpushield.integrity.v1.IntegrityStatus" json:"status,omitempty"`
	// Hash-based integrity
	HashMeasurements []*HashMeasurement `protobuf:"bytes,5,rep,name=hash_measurements,json=hashMeasurements,proto3" json:"hash_measurements,omitempty"`
	// Signature verification
	SignatureVerification *SignatureVerification `protobuf:"bytes,6,opt,name=signature_verification,json=signatureVerification,proto3" json:"signature_verification,omitempty"`
	// Runtime integrity
	RuntimeIntegrity *RuntimeIntegrity `protobuf:"bytes,7,opt,name=runtime_integrity,json=runtimeIntegrity,proto3" json:"runtime_integrity,omitempty"`
	// Additional metadata
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentIntegrity) Reset() {
	*x = ComponentIntegrity{}
	mi := &file_integrity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentIntegrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentIntegrity) ProtoMessage() {}

func (x *ComponentIntegrity) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentIntegrity.ProtoReflect.Descriptor instead.
func (*ComponentIntegrity) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{1}
}

func (x *ComponentIntegrity) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ComponentIntegrity) GetComponentVersion() string {
	if x != nil {
		return x.ComponentVersion
	}
	return ""
}

func (x *ComponentIntegrity) GetComponentType() ComponentType {
	if x != nil {
		return x.ComponentType
	}
	return ComponentType_COMPONENT_TYPE_UNKNOWN
}

func (x *ComponentIntegrity) GetStatus() IntegrityStatus {
	if x != nil {
		return x.Status
	}
	return IntegrityStatus_INTEGRITY_STATUS_UNKNOWN
}

func (x *ComponentIntegrity) GetHashMeasurements() []*HashMeasurement {
	if x != nil {
		return x.HashMeasurements
	}
	return nil
}

func (x *ComponentIntegrity) GetSignatureVerification() *SignatureVerification {
	if x != nil {
		return x.SignatureVerification
	}
	return nil
}

func (x *ComponentIntegrity) GetRuntimeIntegrity() *RuntimeIntegrity {
	if x != nil {
		return x.RuntimeIntegrity
	}
	return nil
}

func (x *ComponentIntegrity) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HashMeasurement represents a cryptographic hash measurement
type HashMeasurement struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Algorithm  string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // "sha256", "sha512", "blake2b", etc.
	HashValue  string                 `protobuf:"bytes,2,opt,name=hash_value,json=hashValue,proto3" json:"hash_value,omitempty"`
	FilePath   string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize   uint64                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MeasuredAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	// Reference hash for comparison
	ExpectedHash  string `protobuf:"bytes,6,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	HashMatches   bool   `protobuf:"varint,7,opt,name=hash_matches,json=hashMatches,proto3" json:"hash_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashMeasurement) Reset() {
	*x = HashMeasurement{}
	mi := &file_integrity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashMeasurement) ProtoMessage() {}

func (x *HashMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashMeasurement.ProtoReflect.Descriptor instead.
func (*HashMeasurement) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{2}
}

func (x *HashMeasurement) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *HashMeasurement) GetHashValue() string {
	if x != nil {
		return x.HashValue
	}
	return ""
}

func (x *HashMeasurement) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HashMeasurement) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *HashMeasurement) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *HashMeasurement) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *HashMeasurement) GetHashMatches() bool {
	if x != nil {
		return x.HashMatches
	}
	return false
}

// SignatureVerification represents digital signature verification
type SignatureVerification struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsSigned           bool                   `protobuf:"varint,1,opt,name=is_signed,json=isSigned,proto3" json:"is_signed,omitempty"`
	SignatureValid     bool                   `protobuf:"varint,2,opt,name=signature_valid,json=signatureValid,proto3" json:"signature_valid,omitempty"`
	Signer             string                 `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	CertificateChain   string                 `protobuf:"bytes,4,opt,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	SignatureTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=signature_timestamp,json=signatureTimestamp,proto3" json:"signature_timestamp,omitempty"`
	SignatureAlgorithm string                 `protobuf:"bytes,6,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	TrustAnchors       []string               `protobuf:"bytes,7,rep,name=trust_anchors,json=trustAnchors,proto3" json:"trust_anchors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignatureVerification) Reset() {
	*x = SignatureVerification{}
	mi := &file_integrity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureVerification) ProtoMessage() {}

func (x *SignatureVerification) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureVerification.ProtoReflect.Descriptor instead.
func (*SignatureVerification) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{3}
}

func (x *SignatureVerification) GetIsSigned() bool {
	if x != nil {
		return x.IsSigned
	}
	return false
}

func (x *SignatureVerification) GetSignatureValid() bool {
	if x != nil {
		return x.SignatureValid
	}
	return false
}

func (x *SignatureVerification) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *SignatureVerification) GetCertificateChain() string {
	if x != nil {
		return x.CertificateChain
	}
	return ""
}

func (x *SignatureVerification) GetSignatureTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.SignatureTimestamp
	}
	return nil
}

func (x *SignatureVerification) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *SignatureVerification) GetTrustAnchors() []string {
	if x != nil {
		return x.TrustAnchors
	}
	return nil
}

// RuntimeIntegrity represents runtime integrity checks
type RuntimeIntegrity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Memory protection
	MemoryProtection *MemoryProtection `protobuf:"bytes,1,opt,name=memory_protection,json=memoryProtection,proto3" json:"memory_protection,omitempty"`
	// Control flow integrity
	ControlFlowIntegrity *ControlFlowIntegrity `protobuf:"bytes,2,opt,name=control_flow_integrity,json=controlFlowIntegrity,proto3" json:"control_flow_integrity,omitempty"`
	// API hooking detection
	ApiHooks []*APIHook `protobuf:"bytes,3,rep,name=api_hooks,json=apiHooks,proto3" json:"api_hooks,omitempty"`
	// Process integrity
	ProcessIntegrity *ProcessIntegrity `protobuf:"bytes,4,opt,name=process_integrity,json=processIntegrity,proto3" json:"process_integrity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuntimeIntegrity) Reset() {
	*x = RuntimeIntegrity{}
	mi := &file_integrity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeIntegrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeIntegrity) ProtoMessage() {}

func (x *RuntimeIntegrity) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeIntegrity.ProtoReflect.Descriptor instead.
func (*RuntimeIntegrity) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeIntegrity) GetMemoryProtection() *MemoryProtection {
	if x != nil {
		return x.MemoryProtection
	}
	return nil
}

func (x *RuntimeIntegrity) GetControlFlowIntegrity() *ControlFlowIntegrity {
	if x != nil {
		return x.ControlFlowIntegrity
	}
	return nil
}

func (x *RuntimeIntegrity) GetApiHooks() []*APIHook {
	if x != nil {
		return x.ApiHooks
	}
	return nil
}

func (x *RuntimeIntegrity) GetProcessIntegrity() *ProcessIntegrity {
	if x != nil {
		return x.ProcessIntegrity
	}
	return nil
}

// MemoryProtection represents memory protection status
type MemoryProtection struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NxBitEnabled         bool                   `protobuf:"varint,1,opt,name=nx_bit_enabled,json=nxBitEnabled,proto3" json:"nx_bit_enabled,omitempty"`
	AslrEnabled          bool                   `protobuf:"varint,2,opt,name=aslr_enabled,json=aslrEnabled,proto3" json:"aslr_enabled,omitempty"`
	DepEnabled           bool                   `protobuf:"varint,3,opt,name=dep_enabled,json=depEnabled,proto3" json:"dep_enabled,omitempty"`
	StackCanariesEnabled bool                   `protobuf:"varint,4,opt,name=stack_canaries_enabled,json=stackCanariesEnabled,proto3" json:"stack_canaries_enabled,omitempty"`
	SuspiciousRegions    []*MemoryRegion        `protobuf:"bytes,5,rep,name=suspicious_regions,json=suspiciousRegions,proto3" json:"suspicious_regions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MemoryProtection) Reset() {
	*x = MemoryProtection{}
	mi := &file_integrity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryProtection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryProtection) ProtoMessage() {}

func (x *MemoryProtection) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryProtection.ProtoReflect.Descriptor instead.
func (*MemoryProtection) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryProtection) GetNxBitEnabled() bool {
	if x != nil {
		return x.NxBitEnabled
	}
	return false
}

func (x *MemoryProtection) GetAslrEnabled() bool {
	if x != nil {
		return x.AslrEnabled
	}
	return false
}

func (x *MemoryProtection) GetDepEnabled() bool {
	if x != nil {
		return x.DepEnabled
	}
	return false
}

func (x *MemoryProtection) GetStackCanariesEnabled() bool {
	if x != nil {
		return x.StackCanariesEnabled
	}
	return false
}

func (x *MemoryProtection) GetSuspiciousRegions() []*MemoryRegion {
	if x != nil {
		return x.SuspiciousRegions
	}
	return nil
}

// MemoryRegion represents a memory region of interest
type MemoryRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartAddress  uint64                 `protobuf:"varint,1,opt,name=start_address,json=startAddress,proto3" json:"start_address,omitempty"`
	EndAddress    uint64                 `protobuf:"varint,2,opt,name=end_address,json=endAddress,proto3" json:"end_address,omitempty"`
	Permissions   string                 `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"` // "rwx", "r-x", etc.
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsSuspicious  bool                   `protobuf:"varint,5,opt,name=is_suspicious,json=isSuspicious,proto3" json:"is_suspicious,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRegion) Reset() {
	*x = MemoryRegion{}
	mi := &file_integrity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRegion) ProtoMessage() {}

func (x *MemoryRegion) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRegion.ProtoReflect.Descriptor instead.
func (*MemoryRegion) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryRegion) GetStartAddress() uint64 {
	if x != nil {
		return x.StartAddress
	}
	return 0
}

func (x *MemoryRegion) GetEndAddress() uint64 {
	if x != nil {
		return x.EndAddress
	}
	return 0
}

func (x *MemoryRegion) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *MemoryRegion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MemoryRegion) GetIsSuspicious() bool {
	if x != nil {
		return x.IsSuspicious
	}
	return false
}

// ControlFlowIntegrity represents CFI status
type ControlFlowIntegrity struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	CfiEnabled         bool                    `protobuf:"varint,1,opt,name=cfi_enabled,json=cfiEnabled,proto3" json:"cfi_enabled,omitempty"`
	ShadowStackEnabled bool                    `protobuf:"varint,2,opt,name=shadow_stack_enabled,json=shadowStackEnabled,proto3" json:"shadow_stack_enabled,omitempty"`
	Violations         []*ControlFlowViolation `protobuf:"bytes,3,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ControlFlowIntegrity) Reset() {
	*x = ControlFlowIntegrity{}
	mi := &file_integrity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFlowIntegrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFlowIntegrity) ProtoMessage() {}

func (x *ControlFlowIntegrity) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFlowIntegrity.ProtoReflect.Descriptor instead.
func (*ControlFlowIntegrity) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{7}
}

func (x *ControlFlowIntegrity) GetCfiEnabled() bool {
	if x != nil {
		return x.CfiEnabled
	}
	return false
}

func (x *ControlFlowIntegrity) GetShadowStackEnabled() bool {
	if x != nil {
		return x.ShadowStackEnabled
	}
	return false
}

func (x *ControlFlowIntegrity) GetViolations() []*ControlFlowViolation {
	if x != nil {
		return x.Violations
	}
	return nil
}

// ControlFlowViolation represents a CFI violation
type ControlFlowViolation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ViolationAddress uint64                 `protobuf:"varint,1,opt,name=violation_address,json=violationAddress,proto3" json:"violation_address,omitempty"`
	ViolationType    string                 `protobuf:"bytes,2,opt,name=violation_type,json=violationType,proto3" json:"violation_type,omitempty"`
	DetectedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ControlFlowViolation) Reset() {
	*x = ControlFlowViolation{}
	mi := &file_integrity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFlowViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFlowViolation) ProtoMessage() {}

func (x *ControlFlowViolation) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFlowViolation.ProtoReflect.Descriptor instead.
func (*ControlFlowViolation) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{8}
}

func (x *ControlFlowViolation) GetViolationAddress() uint64 {
	if x != nil {
		return x.ViolationAddress
	}
	return 0
}

func (x *ControlFlowViolation) GetViolationType() string {
	if x != nil {
		return x.ViolationType
	}
	return ""
}

func (x *ControlFlowViolation) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *ControlFlowViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// APIHook represents a detected API hook
type APIHook struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApiName         string                 `protobuf:"bytes,1,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	ModuleName      string                 `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	OriginalAddress uint64                 `protobuf:"varint,3,opt,name=original_address,json=originalAddress,proto3" json:"original_address,omitempty"`
	HookAddress     uint64                 `protobuf:"varint,4,opt,name=hook_address,json=hookAddress,proto3" json:"hook_address,omitempty"`
	HookType        string                 `protobuf:"bytes,5,opt,name=hook_type,json=hookType,proto3" json:"hook_type,omitempty"` // "inline", "iat", "eat", etc.
	IsMalicious     bool                   `protobuf:"varint,6,opt,name=is_malicious,json=isMalicious,proto3" json:"is_malicious,omitempty"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *APIHook) Reset() {
	*x = APIHook{}
	mi := &file_integrity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIHook) ProtoMessage() {}

func (x *APIHook) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIHook.ProtoReflect.Descriptor instead.
func (*APIHook) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{9}
}

func (x *APIHook) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *APIHook) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *APIHook) GetOriginalAddress() uint64 {
	if x != nil {
		return x.OriginalAddress
	}
	return 0
}

func (x *APIHook) GetHookAddress() uint64 {
	if x != nil {
		return x.HookAddress
	}
	return 0
}

func (x *APIHook) GetHookType() string {
	if x != nil {
		return x.HookType
	}
	return ""
}

func (x *APIHook) GetIsMalicious() bool {
	if x != nil {
		return x.IsMalicious
	}
	return false
}

func (x *APIHook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ProcessIntegrity represents process-level integrity
type ProcessIntegrity struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Pid                 uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName         string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ExecutablePath      string                 `protobuf:"bytes,3,opt,name=executable_path,json=executablePath,proto3" json:"executable_path,omitempty"`
	IsTrusted           bool                   `protobuf:"varint,4,opt,name=is_trusted,json=isTrusted,proto3" json:"is_trusted,omitempty"`
	LoadedModules       []string               `protobuf:"bytes,5,rep,name=loaded_modules,json=loadedModules,proto3" json:"loaded_modules,omitempty"`
	SuspiciousBehaviors []string               `protobuf:"bytes,6,rep,name=suspicious_behaviors,json=suspiciousBehaviors,proto3" json:"suspicious_behaviors,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessIntegrity) Reset() {
	*x = ProcessIntegrity{}
	mi := &file_integrity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessIntegrity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessIntegrity) ProtoMessage() {}

func (x *ProcessIntegrity) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessIntegrity.ProtoReflect.Descriptor instead.
func (*ProcessIntegrity) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessIntegrity) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessIntegrity) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *ProcessIntegrity) GetExecutablePath() string {
	if x != nil {
		return x.ExecutablePath
	}
	return ""
}

func (x *ProcessIntegrity) GetIsTrusted() bool {
	if x != nil {
		return x.IsTrusted
	}
	return false
}

func (x *ProcessIntegrity) GetLoadedModules() []string {
	if x != nil {
		return x.LoadedModules
	}
	return nil
}

func (x *ProcessIntegrity) GetSuspiciousBehaviors() []string {
	if x != nil {
		return x.SuspiciousBehaviors
	}
	return nil
}

// AttestationData represents TPM/hardware attestation data
type AttestationData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TPM attestation
	TpmAttestation *TPMAttestation `protobuf:"bytes,1,opt,name=tpm_attestation,json=tpmAttestation,proto3" json:"tpm_attestation,omitempty"`
	// Secure boot status
	SecureBoot *SecureBootStatus `protobuf:"bytes,2,opt,name=secure_boot,json=secureBoot,proto3" json:"secure_boot,omitempty"`
	// Hardware security features
	HardwareFeatures *HardwareSecurityFeatures `protobuf:"bytes,3,opt,name=hardware_features,json=hardwareFeatures,proto3" json:"hardware_features,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttestationData) Reset() {
	*x = AttestationData{}
	mi := &file_integrity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationData) ProtoMessage() {}

func (x *AttestationData) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationData.ProtoReflect.Descriptor instead.
func (*AttestationData) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{11}
}

func (x *AttestationData) GetTpmAttestation() *TPMAttestation {
	if x != nil {
		return x.TpmAttestation
	}
	return nil
}

func (x *AttestationData) GetSecureBoot() *SecureBootStatus {
	if x != nil {
		return x.SecureBoot
	}
	return nil
}

func (x *AttestationData) GetHardwareFeatures() *HardwareSecurityFeatures {
	if x != nil {
		return x.HardwareFeatures
	}
	return nil
}

// TPMAttestation represents TPM-based attestation
type TPMAttestation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TpmPresent           bool                   `protobuf:"varint,1,opt,name=tpm_present,json=tpmPresent,proto3" json:"tpm_present,omitempty"`
	TpmVersion           string                 `protobuf:"bytes,2,opt,name=tpm_version,json=tpmVersion,proto3" json:"tpm_version,omitempty"`
	PcrMeasurements      []*PCRMeasurement      `protobuf:"bytes,3,rep,name=pcr_measurements,json=pcrMeasurements,proto3" json:"pcr_measurements,omitempty"`
	AttestationKeyDigest string                 `protobuf:"bytes,4,opt,name=attestation_key_digest,json=attestationKeyDigest,proto3" json:"attestation_key_digest,omitempty"`
	Quote                []byte                 `protobuf:"bytes,5,opt,name=quote,proto3" json:"quote,omitempty"`
	Signature            []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TPMAttestation) Reset() {
	*x = TPMAttestation{}
	mi := &file_integrity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPMAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPMAttestation) ProtoMessage() {}

func (x *TPMAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPMAttestation.ProtoReflect.Descriptor instead.
func (*TPMAttestation) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{12}
}

func (x *TPMAttestation) GetTpmPresent() bool {
	if x != nil {
		return x.TpmPresent
	}
	return false
}

func (x *TPMAttestation) GetTpmVersion() string {
	if x != nil {
		return x.TpmVersion
	}
	return ""
}

func (x *TPMAttestation) GetPcrMeasurements() []*PCRMeasurement {
	if x != nil {
		return x.PcrMeasurements
	}
	return nil
}

func (x *TPMAttestation) GetAttestationKeyDigest() string {
	if x != nil {
		return x.AttestationKeyDigest
	}
	return ""
}

func (x *TPMAttestation) GetQuote() []byte {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *TPMAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// PCRMeasurement represents a Platform Configuration Register measurement
type PCRMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcrIndex      uint32                 `protobuf:"varint,1,opt,name=pcr_index,json=pcrIndex,proto3" json:"pcr_index,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCRMeasurement) Reset() {
	*x = PCRMeasurement{}
	mi := &file_integrity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCRMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCRMeasurement) ProtoMessage() {}

func (x *PCRMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCRMeasurement.ProtoReflect.Descriptor instead.
func (*PCRMeasurement) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{13}
}

func (x *PCRMeasurement) GetPcrIndex() uint32 {
	if x != nil {
		return x.PcrIndex
	}
	return 0
}

func (x *PCRMeasurement) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *PCRMeasurement) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PCRMeasurement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// SecureBootStatus represents secure boot configuration
type SecureBootStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SecureBootEnabled   bool                   `protobuf:"varint,1,opt,name=secure_boot_enabled,json=secureBootEnabled,proto3" json:"secure_boot_enabled,omitempty"`
	SetupMode           bool                   `protobuf:"varint,2,opt,name=setup_mode,json=setupMode,proto3" json:"setup_mode,omitempty"`
	TrustedCertificates []string               `protobuf:"bytes,3,rep,name=trusted_certificates,json=trustedCertificates,proto3" json:"trusted_certificates,omitempty"`
	ForbiddenSignatures []string               `protobuf:"bytes,4,rep,name=forbidden_signatures,json=forbiddenSignatures,proto3" json:"forbidden_signatures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SecureBootStatus) Reset() {
	*x = SecureBootStatus{}
	mi := &file_integrity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureBootStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureBootStatus) ProtoMessage() {}

func (x *SecureBootStatus) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureBootStatus.ProtoReflect.Descriptor instead.
func (*SecureBootStatus) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{14}
}

func (x *SecureBootStatus) GetSecureBootEnabled() bool {
	if x != nil {
		return x.SecureBootEnabled
	}
	return false
}

func (x *SecureBootStatus) GetSetupMode() bool {
	if x != nil {
		return x.SetupMode
	}
	return false
}

func (x *SecureBootStatus) GetTrustedCertificates() []string {
	if x != nil {
		return x.TrustedCertificates
	}
	return nil
}

func (x *SecureBootStatus) GetForbiddenSignatures() []string {
	if x != nil {
		return x.ForbiddenSignatures
	}
	return nil
}

// HardwareSecurityFeatures represents hardware security capabilities
type HardwareSecurityFeatures struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IntelTxtEnabled    bool                   `protobuf:"varint,1,opt,name=intel_txt_enabled,json=intelTxtEnabled,proto3" json:"intel_txt_enabled,omitempty"`
	AmdSvmEnabled      bool                   `protobuf:"varint,2,opt,name=amd_svm_enabled,json=amdSvmEnabled,proto3" json:"amd_svm_enabled,omitempty"`
	IommuEnabled       bool                   `protobuf:"varint,3,opt,name=iommu_enabled,json=iommuEnabled,proto3" json:"iommu_enabled,omitempty"`
	SmepEnabled        bool                   `protobuf:"varint,4,opt,name=smep_enabled,json=smepEnabled,proto3" json:"smep_enabled,omitempty"`
	SmapEnabled        bool                   `protobuf:"varint,5,opt,name=smap_enabled,json=smapEnabled,proto3" json:"smap_enabled,omitempty"`
	CetEnabled         bool                   `protobuf:"varint,6,opt,name=cet_enabled,json=cetEnabled,proto3" json:"cet_enabled,omitempty"`
	AdditionalFeatures []string               `protobuf:"bytes,7,rep,name=additional_features,json=additionalFeatures,proto3" json:"additional_features,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HardwareSecurityFeatures) Reset() {
	*x = HardwareSecurityFeatures{}
	mi := &file_integrity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareSecurityFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareSecurityFeatures) ProtoMessage() {}

func (x *HardwareSecurityFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareSecurityFeatures.ProtoReflect.Descriptor instead.
func (*HardwareSecurityFeatures) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{15}
}

func (x *HardwareSecurityFeatures) GetIntelTxtEnabled() bool {
	if x != nil {
		return x.IntelTxtEnabled
	}
	return false
}

func (x *HardwareSecurityFeatures) GetAmdSvmEnabled() bool {
	if x != nil {
		return x.AmdSvmEnabled
	}
	return false
}

func (x *HardwareSecurityFeatures) GetIommuEnabled() bool {
	if x != nil {
		return x.IommuEnabled
	}
	return false
}

func (x *HardwareSecurityFeatures) GetSmepEnabled() bool {
	if x != nil {
		return x.SmepEnabled
	}
	return false
}

func (x *HardwareSecurityFeatures) GetSmapEnabled() bool {
	if x != nil {
		return x.SmapEnabled
	}
	return false
}

func (x *HardwareSecurityFeatures) GetCetEnabled() bool {
	if x != nil {
		return x.CetEnabled
	}
	return false
}

func (x *HardwareSecurityFeatures) GetAdditionalFeatures() []string {
	if x != nil {
		return x.AdditionalFeatures
	}
	return nil
}

// SecurityEvent represents a security-related event
type SecurityEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventId     string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType   SecurityEventType      `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=gpushield.integrity.v1.SecurityEventType" json:"event_type,omitempty"`
	Severity    SecurityEventSeverity  `protobuf:"varint,3,opt,name=severity,proto3,enum=gpushield.integrity.v1.SecurityEventSeverity" json:"severity,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Details     map[string]string      `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Source information
	SourceComponent string `protobuf:"bytes,7,opt,name=source_component,json=sourceComponent,proto3" json:"source_component,omitempty"`
	SourceNode      string `protobuf:"bytes,8,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	// Remediation
	RecommendedActions []string `protobuf:"bytes,9,rep,name=recommended_actions,json=recommendedActions,proto3" json:"recommended_actions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SecurityEvent) Reset() {
	*x = SecurityEvent{}
	mi := &file_integrity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEvent) ProtoMessage() {}

func (x *SecurityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEvent.ProtoReflect.Descriptor instead.
func (*SecurityEvent) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{16}
}

func (x *SecurityEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SecurityEvent) GetEventType() SecurityEventType {
	if x != nil {
		return x.EventType
	}
	return SecurityEventType_SECURITY_EVENT_TYPE_UNKNOWN
}

func (x *SecurityEvent) GetSeverity() SecurityEventSeverity {
	if x != nil {
		return x.Severity
	}
	return SecurityEventSeverity_SECURITY_EVENT_SEVERITY_UNKNOWN
}

func (x *SecurityEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SecurityEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecurityEvent) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *SecurityEvent) GetSourceComponent() string {
	if x != nil {
		return x.SourceComponent
	}
	return ""
}

func (x *SecurityEvent) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *SecurityEvent) GetRecommendedActions() []string {
	if x != nil {
		return x.RecommendedActions
	}
	return nil
}

// IntegrityCheckRequest represents a request to perform integrity check
type IntegrityCheckRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Components         []string               `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"` // Optional filter for specific components
	IncludeAttestation bool                   `protobuf:"varint,3,opt,name=include_attestation,json=includeAttestation,proto3" json:"include_attestation,omitempty"`
	DeepScan           bool                   `protobuf:"varint,4,opt,name=deep_scan,json=deepScan,proto3" json:"deep_scan,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IntegrityCheckRequest) Reset() {
	*x = IntegrityCheckRequest{}
	mi := &file_integrity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityCheckRequest) ProtoMessage() {}

func (x *IntegrityCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityCheckRequest.ProtoReflect.Descriptor instead.
func (*IntegrityCheckRequest) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{17}
}

func (x *IntegrityCheckRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *IntegrityCheckRequest) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *IntegrityCheckRequest) GetIncludeAttestation() bool {
	if x != nil {
		return x.IncludeAttestation
	}
	return false
}

func (x *IntegrityCheckRequest) GetDeepScan() bool {
	if x != nil {
		return x.DeepScan
	}
	return false
}

// IntegrityResponse represents a response to integrity data
type IntegrityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrityResponse) Reset() {
	*x = IntegrityResponse{}
	mi := &file_integrity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityResponse) ProtoMessage() {}

func (x *IntegrityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityResponse.ProtoReflect.Descriptor instead.
func (*IntegrityResponse) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{18}
}

func (x *IntegrityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IntegrityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IntegrityResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

// GetIntegrityStatusRequest represents a request for integrity status
type GetIntegrityStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Components    []string               `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrityStatusRequest) Reset() {
	*x = GetIntegrityStatusRequest{}
	mi := &file_integrity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrityStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrityStatusRequest) ProtoMessage() {}

func (x *GetIntegrityStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrityStatusRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrityStatusRequest) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{19}
}

func (x *GetIntegrityStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetIntegrityStatusRequest) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

// IntegrityStatusResponse represents the current integrity status
type IntegrityStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallStatus IntegrityStatus        `protobuf:"varint,1,opt,name=overall_status,json=overallStatus,proto3,enum=gpushield.integrity.v1.IntegrityStatus" json:"overall_status,omitempty"`
	Components    []*ComponentIntegrity  `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrityStatusResponse) Reset() {
	*x = IntegrityStatusResponse{}
	mi := &file_integrity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityStatusResponse) ProtoMessage() {}

func (x *IntegrityStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityStatusResponse.ProtoReflect.Descriptor instead.
func (*IntegrityStatusResponse) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{20}
}

func (x *IntegrityStatusResponse) GetOverallStatus() IntegrityStatus {
	if x != nil {
		return x.OverallStatus
	}
	return IntegrityStatus_INTEGRITY_STATUS_UNKNOWN
}

func (x *IntegrityStatusResponse) GetComponents() []*ComponentIntegrity {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *IntegrityStatusResponse) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

// UpdateTrustedBaselineRequest represents a request to update trusted baselines
type UpdateTrustedBaselineRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ComponentName         string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	ComponentVersion      string                 `protobuf:"bytes,2,opt,name=component_version,json=componentVersion,proto3" json:"component_version,omitempty"`
	TrustedHashes         []*HashMeasurement     `protobuf:"bytes,3,rep,name=trusted_hashes,json=trustedHashes,proto3" json:"trusted_hashes,omitempty"`
	SignatureRequirements *SignatureVerification `protobuf:"bytes,4,opt,name=signature_requirements,json=signatureRequirements,proto3" json:"signature_requirements,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateTrustedBaselineRequest) Reset() {
	*x = UpdateTrustedBaselineRequest{}
	mi := &file_integrity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrustedBaselineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrustedBaselineRequest) ProtoMessage() {}

func (x *UpdateTrustedBaselineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrustedBaselineRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrustedBaselineRequest) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateTrustedBaselineRequest) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *UpdateTrustedBaselineRequest) GetComponentVersion() string {
	if x != nil {
		return x.ComponentVersion
	}
	return ""
}

func (x *UpdateTrustedBaselineRequest) GetTrustedHashes() []*HashMeasurement {
	if x != nil {
		return x.TrustedHashes
	}
	return nil
}

func (x *UpdateTrustedBaselineRequest) GetSignatureRequirements() *SignatureVerification {
	if x != nil {
		return x.SignatureRequirements
	}
	return nil
}

// UpdateTrustedBaselineResponse represents the response to baseline update
type UpdateTrustedBaselineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrustedBaselineResponse) Reset() {
	*x = UpdateTrustedBaselineResponse{}
	mi := &file_integrity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrustedBaselineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrustedBaselineResponse) ProtoMessage() {}

func (x *UpdateTrustedBaselineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrustedBaselineResponse.ProtoReflect.Descriptor instead.
func (*UpdateTrustedBaselineResponse) Descriptor() ([]byte, []int) {
	return file_integrity_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateTrustedBaselineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTrustedBaselineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateTrustedBaselineResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_integrity_proto protoreflect.FileDescriptor

const file_integrity_proto_rawDesc = "" +
	"\n" +
	"\x0fintegrity.proto\x12\x16gpushield.integrity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x03\n" +
	"\x0fIntegrityReport\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1b\n" +
	"\treport_id\x18\x04 \x01(\tR\breportId\x12N\n" +
	"\x0eoverall_status\x18\x05 \x01(\x0e2'.gpushield.integrity.v1.IntegrityStatusR\roverallStatus\x12J\n" +
	"\n" +
	"components\x18\x06 \x03(\v2*.gpushield.integrity.v1.ComponentIntegrityR\n" +
	"components\x12I\n" +
	"\vattestation\x18\a \x01(\v2'.gpushield.integrity.v1.AttestationDataR\vattestation\x12N\n" +
	"\x0fsecurity_events\x18\b \x03(\v2%.gpushield.integrity.v1.SecurityEventR\x0esecurityEvents\"\x9d\x05\n" +
	"\x12ComponentIntegrity\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12+\n" +
	"\x11component_version\x18\x02 \x01(\tR\x10componentVersion\x12L\n" +
	"\x0ecomponent_type\x18\x03 \x01(\x0e2%.gpushield.integrity.v1.ComponentTypeR\rcomponentType\x12?\n" +
	"\x06status\x18\x04 \x01(\x0e2'.gpushield.integrity.v1.IntegrityStatusR\x06status\x12T\n" +
	"\x11hash_measurements\x18\x05 \x03(\v2'.gpushield.integrity.v1.HashMeasurementR\x10hashMeasurements\x12d\n" +
	"\x16signature_verification\x18\x06 \x01(\v2-.gpushield.integrity.v1.SignatureVerificationR\x15signatureVerification\x12U\n" +
	"\x11runtime_integrity\x18\a \x01(\v2(.gpushield.integrity.v1.RuntimeIntegrityR\x10runtimeIntegrity\x12T\n" +
	"\bmetadata\x18\b \x03(\v28.gpushield.integrity.v1.ComponentIntegrity.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x0fHashMeasurement\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"hash_value\x18\x02 \x01(\tR\thashValue\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x04R\bfileSize\x12;\n" +
	"\vmeasured_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"measuredAt\x12#\n" +
	"\rexpected_hash\x18\x06 \x01(\tR\fexpectedHash\x12!\n" +
	"\fhash_matches\x18\a \x01(\bR\vhashMatches\"\xc5\x02\n" +
	"\x15SignatureVerification\x12\x1b\n" +
	"\tis_signed\x18\x01 \x01(\bR\bisSigned\x12'\n" +
	"\x0fsignature_valid\x18\x02 \x01(\bR\x0esignatureValid\x12\x16\n" +
	"\x06signer\x18\x03 \x01(\tR\x06signer\x12+\n" +
	"\x11certificate_chain\x18\x04 \x01(\tR\x10certificateChain\x12K\n" +
	"\x13signature_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12signatureTimestamp\x12/\n" +
	"\x13signature_algorithm\x18\x06 \x01(\tR\x12signatureAlgorithm\x12#\n" +
	"\rtrust_anchors\x18\a \x03(\tR\ftrustAnchors\"\xe2\x02\n" +
	"\x10RuntimeIntegrity\x12U\n" +
	"\x11memory_protection\x18\x01 \x01(\v2(.gpushield.integrity.v1.MemoryProtectionR\x10memoryProtection\x12b\n" +
	"\x16control_flow_integrity\x18\x02 \x01(\v2,.gpushield.integrity.v1.ControlFlowIntegrityR\x14controlFlowIntegrity\x12<\n" +
	"\tapi_hooks\x18\x03 \x03(\v2\x1f.gpushield.integrity.v1.APIHookR\bapiHooks\x12U\n" +
	"\x11process_integrity\x18\x04 \x01(\v2(.gpushield.integrity.v1.ProcessIntegrityR\x10processIntegrity\"\x87\x02\n" +
	"\x10MemoryProtection\x12$\n" +
	"\x0enx_bit_enabled\x18\x01 \x01(\bR\fnxBitEnabled\x12!\n" +
	"\faslr_enabled\x18\x02 \x01(\bR\vaslrEnabled\x12\x1f\n" +
	"\vdep_enabled\x18\x03 \x01(\bR\n" +
	"depEnabled\x124\n" +
	"\x16stack_canaries_enabled\x18\x04 \x01(\bR\x14stackCanariesEnabled\x12S\n" +
	"\x12suspicious_regions\x18\x05 \x03(\v2$.gpushield.integrity.v1.MemoryRegionR\x11suspiciousRegions\"\xbd\x01\n" +
	"\fMemoryRegion\x12#\n" +
	"\rstart_address\x18\x01 \x01(\x04R\fstartAddress\x12\x1f\n" +
	"\vend_address\x18\x02 \x01(\x04R\n" +
	"endAddress\x12 \n" +
	"\vpermissions\x18\x03 \x01(\tR\vpermissions\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\ris_suspicious\x18\x05 \x01(\bR\fisSuspicious\"\xb7\x01\n" +
	"\x14ControlFlowIntegrity\x12\x1f\n" +
	"\vcfi_enabled\x18\x01 \x01(\bR\n" +
	"cfiEnabled\x120\n" +
	"\x14shadow_stack_enabled\x18\x02 \x01(\bR\x12shadowStackEnabled\x12L\n" +
	"\n" +
	"violations\x18\x03 \x03(\v2,.gpushield.integrity.v1.ControlFlowViolationR\n" +
	"violations\"\xc9\x01\n" +
	"\x14ControlFlowViolation\x12+\n" +
	"\x11violation_address\x18\x01 \x01(\x04R\x10violationAddress\x12%\n" +
	"\x0eviolation_type\x18\x02 \x01(\tR\rviolationType\x12;\n" +
	"\vdetected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xf5\x01\n" +
	"\aAPIHook\x12\x19\n" +
	"\bapi_name\x18\x01 \x01(\tR\aapiName\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\x12)\n" +
	"\x10original_address\x18\x03 \x01(\x04R\x0foriginalAddress\x12!\n" +
	"\fhook_address\x18\x04 \x01(\x04R\vhookAddress\x12\x1b\n" +
	"\thook_type\x18\x05 \x01(\tR\bhookType\x12!\n" +
	"\fis_malicious\x18\x06 \x01(\bR\visMalicious\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\xe9\x01\n" +
	"\x10ProcessIntegrity\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\x12'\n" +
	"\x0fexecutable_path\x18\x03 \x01(\tR\x0eexecutablePath\x12\x1d\n" +
	"\n" +
	"is_trusted\x18\x04 \x01(\bR\tisTrusted\x12%\n" +
	"\x0eloaded_modules\x18\x05 \x03(\tR\rloadedModules\x121\n" +
	"\x14suspicious_behaviors\x18\x06 \x03(\tR\x13suspiciousBehaviors\"\x8c\x02\n" +
	"\x0fAttestationData\x12O\n" +
	"\x0ftpm_attestation\x18\x01 \x01(\v2&.gpushield.integrity.v1.TPMAttestationR\x0etpmAttestation\x12I\n" +
	"\vsecure_boot\x18\x02 \x01(\v2(.gpushield.integrity.v1.SecureBootStatusR\n" +
	"secureBoot\x12]\n" +
	"\x11hardware_features\x18\x03 \x01(\v20.gpushield.integrity.v1.HardwareSecurityFeaturesR\x10hardwareFeatures\"\x8f\x02\n" +
	"\x0eTPMAttestation\x12\x1f\n" +
	"\vtpm_present\x18\x01 \x01(\bR\n" +
	"tpmPresent\x12\x1f\n" +
	"\vtpm_version\x18\x02 \x01(\tR\n" +
	"tpmVersion\x12Q\n" +
	"\x10pcr_measurements\x18\x03 \x03(\v2&.gpushield.integrity.v1.PCRMeasurementR\x0fpcrMeasurements\x124\n" +
	"\x16attestation_key_digest\x18\x04 \x01(\tR\x14attestationKeyDigest\x12\x14\n" +
	"\x05quote\x18\x05 \x01(\fR\x05quote\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\x83\x01\n" +
	"\x0ePCRMeasurement\x12\x1b\n" +
	"\tpcr_index\x18\x01 \x01(\rR\bpcrIndex\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xc7\x01\n" +
	"\x10SecureBootStatus\x12.\n" +
	"\x13secure_boot_enabled\x18\x01 \x01(\bR\x11secureBootEnabled\x12\x1d\n" +
	"\n" +
	"setup_mode\x18\x02 \x01(\bR\tsetupMode\x121\n" +
	"\x14trusted_certificates\x18\x03 \x03(\tR\x13trustedCertificates\x121\n" +
	"\x14forbidden_signatures\x18\x04 \x03(\tR\x13forbiddenSignatures\"\xab\x02\n" +
	"\x18HardwareSecurityFeatures\x12*\n" +
	"\x11intel_txt_enabled\x18\x01 \x01(\bR\x0fintelTxtEnabled\x12&\n" +
	"\x0famd_svm_enabled\x18\x02 \x01(\bR\ramdSvmEnabled\x12#\n" +
	"\riommu_enabled\x18\x03 \x01(\bR\fiommuEnabled\x12!\n" +
	"\fsmep_enabled\x18\x04 \x01(\bR\vsmepEnabled\x12!\n" +
	"\fsmap_enabled\x18\x05 \x01(\bR\vsmapEnabled\x12\x1f\n" +
	"\vcet_enabled\x18\x06 \x01(\bR\n" +
	"cetEnabled\x12/\n" +
	"\x13additional_features\x18\a \x03(\tR\x12additionalFeatures\"\xa2\x04\n" +
	"\rSecurityEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12H\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2).gpushield.integrity.v1.SecurityEventTypeR\teventType\x12I\n" +
	"\bseverity\x18\x03 \x01(\x0e2-.gpushield.integrity.v1.SecurityEventSeverityR\bseverity\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12L\n" +
	"\adetails\x18\x06 \x03(\v22.gpushield.integrity.v1.SecurityEvent.DetailsEntryR\adetails\x12)\n" +
	"\x10source_component\x18\a \x01(\tR\x0fsourceComponent\x12\x1f\n" +
	"\vsource_node\x18\b \x01(\tR\n" +
	"sourceNode\x12/\n" +
	"\x13recommended_actions\x18\t \x03(\tR\x12recommendedActions\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x15IntegrityCheckRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"components\x18\x02 \x03(\tR\n" +
	"components\x12/\n" +
	"\x13include_attestation\x18\x03 \x01(\bR\x12includeAttestation\x12\x1b\n" +
	"\tdeep_scan\x18\x04 \x01(\bR\bdeepScan\"\x86\x01\n" +
	"\x11IntegrityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\fprocessed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"T\n" +
	"\x19GetIntegrityStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"components\x18\x02 \x03(\tR\n" +
	"components\"\xf0\x01\n" +
	"\x17IntegrityStatusResponse\x12N\n" +
	"\x0eoverall_status\x18\x01 \x01(\x0e2'.gpushield.integrity.v1.IntegrityStatusR\roverallStatus\x12J\n" +
	"\n" +
	"components\x18\x02 \x03(\v2*.gpushield.integrity.v1.ComponentIntegrityR\n" +
	"components\x129\n" +
	"\n" +
	"last_check\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\"\xa8\x02\n" +
	"\x1cUpdateTrustedBaselineRequest\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12+\n" +
	"\x11component_version\x18\x02 \x01(\tR\x10componentVersion\x12N\n" +
	"\x0etrusted_hashes\x18\x03 \x03(\v2'.gpushield.integrity.v1.HashMeasurementR\rtrustedHashes\x12d\n" +
	"\x16signature_requirements\x18\x04 \x01(\v2-.gpushield.integrity.v1.SignatureVerificationR\x15signatureRequirements\"\x8e\x01\n" +
	"\x1dUpdateTrustedBaselineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xac\x01\n" +
	"\x0fIntegrityStatus\x12\x1c\n" +
	"\x18INTEGRITY_STATUS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18INTEGRITY_STATUS_TRUSTED\x10\x01\x12 \n" +
	"\x1cINTEGRITY_STATUS_COMPROMISED\x10\x02\x12\x1f\n" +
	"\x1bINTEGRITY_STATUS_SUSPICIOUS\x10\x03\x12\x1a\n" +
	"\x16INTEGRITY_STATUS_ERROR\x10\x04*\xe3\x01\n" +
	"\rComponentType\x12\x1a\n" +
	"\x16COMPONENT_TYPE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15COMPONENT_TYPE_DRIVER\x10\x01\x12\x1b\n" +
	"\x17COMPONENT_TYPE_FIRMWARE\x10\x02\x12 \n" +
	"\x1cCOMPONENT_TYPE_KERNEL_MODULE\x10\x03\x12\x1a\n" +
	"\x16COMPONENT_TYPE_LIBRARY\x10\x04\x12\x1e\n" +
	"\x1aCOMPONENT_TYPE_APPLICATION\x10\x05\x12 \n" +
	"\x1cCOMPONENT_TYPE_CONFIGURATION\x10\x06*\xec\x02\n" +
	"\x11SecurityEventType\x12\x1f\n" +
	"\x1bSECURITY_EVENT_TYPE_UNKNOWN\x10\x00\x12+\n" +
	"'SECURITY_EVENT_TYPE_INTEGRITY_VIOLATION\x10\x01\x12+\n" +
	"'SECURITY_EVENT_TYPE_UNAUTHORIZED_ACCESS\x10\x02\x12)\n" +
	"%SECURITY_EVENT_TYPE_MALWARE_DETECTION\x10\x03\x12*\n" +
	"&SECURITY_EVENT_TYPE_ANOMALOUS_BEHAVIOR\x10\x04\x12,\n" +
	"(SECURITY_EVENT_TYPE_CONFIGURATION_CHANGE\x10\x05\x12,\n" +
	"(SECURITY_EVENT_TYPE_PRIVILEGE_ESCALATION\x10\x06\x12)\n" +
	"%SECURITY_EVENT_TYPE_DATA_EXFILTRATION\x10\a*\xeb\x01\n" +
	"\x15SecurityEventSeverity\x12#\n" +
	"\x1fSECURITY_EVENT_SEVERITY_UNKNOWN\x10\x00\x12 \n" +
	"\x1cSECURITY_EVENT_SEVERITY_INFO\x10\x01\x12\x1f\n" +
	"\x1bSECURITY_EVENT_SEVERITY_LOW\x10\x02\x12\"\n" +
	"\x1eSECURITY_EVENT_SEVERITY_MEDIUM\x10\x03\x12 \n" +
	"\x1cSECURITY_EVENT_SEVERITY_HIGH\x10\x04\x12$\n" +
	" SECURITY_EVENT_SEVERITY_CRITICAL\x10\x052\xf6\x03\n" +
	"\x10IntegrityService\x12o\n" +
	"\x15PerformIntegrityCheck\x12-.gpushield.integrity.v1.IntegrityCheckRequest\x1a'.gpushield.integrity.v1.IntegrityReport\x12p\n" +
	"\x16StreamIntegrityReports\x12'.gpushield.integrity.v1.IntegrityReport\x1a).gpushield.integrity.v1.IntegrityResponse(\x010\x01\x12x\n" +
	"\x12GetIntegrityStatus\x121.gpushield.integrity.v1.GetIntegrityStatusRequest\x1a/.gpushield.integrity.v1.IntegrityStatusResponse\x12\x84\x01\n" +
	"\x15UpdateTrustedBaseline\x124.gpushield.integrity.v1.UpdateTrustedBaselineRequest\x1a5.gpushield.integrity.v1.UpdateTrustedBaselineResponseB3Z1github.com/ShipKode/gpushield/api/proto/integrityb\x06proto3"

var (
	file_integrity_proto_rawDescOnce sync.Once
	file_integrity_proto_rawDescData []byte
)

func file_integrity_proto_rawDescGZIP() []byte {
	file_integrity_proto_rawDescOnce.Do(func() {
		file_integrity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integrity_proto_rawDesc), len(file_integrity_proto_rawDesc)))
	})
	return file_integrity_proto_rawDescData
}

var file_integrity_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_integrity_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_integrity_proto_goTypes = []any{
	(IntegrityStatus)(0),                  // 0: gpushield.integrity.v1.IntegrityStatus
	(ComponentType)(0),                    // 1: gpushield.integrity.v1.ComponentType
	(SecurityEventType)(0),                // 2: gpushield.integrity.v1.SecurityEventType
	(SecurityEventSeverity)(0),            // 3: gpushield.integrity.v1.SecurityEventSeverity
	(*IntegrityReport)(nil),               // 4: gpushield.integrity.v1.IntegrityReport
	(*ComponentIntegrity)(nil),            // 5: gpushield.integrity.v1.ComponentIntegrity
	(*HashMeasurement)(nil),               // 6: gpushield.integrity.v1.HashMeasurement
	(*SignatureVerification)(nil),         // 7: gpushield.integrity.v1.SignatureVerification
	(*RuntimeIntegrity)(nil),              // 8: gpushield.integrity.v1.RuntimeIntegrity
	(*MemoryProtection)(nil),              // 9: gpushield.integrity.v1.MemoryProtection
	(*MemoryRegion)(nil),                  // 10: gpushield.integrity.v1.MemoryRegion
	(*ControlFlowIntegrity)(nil),          // 11: gpushield.integrity.v1.ControlFlowIntegrity
	(*ControlFlowViolation)(nil),          // 12: gpushield.integrity.v1.ControlFlowViolation
	(*APIHook)(nil),                       // 13: gpushield.integrity.v1.APIHook
	(*ProcessIntegrity)(nil),              // 14: gpushield.integrity.v1.ProcessIntegrity
	(*AttestationData)(nil),               // 15: gpushield.integrity.v1.AttestationData
	(*TPMAttestation)(nil),                // 16: gpushield.integrity.v1.TPMAttestation
	(*PCRMeasurement)(nil),                // 17: gpushield.integrity.v1.PCRMeasurement
	(*SecureBootStatus)(nil),              // 18: gpushield.integrity.v1.SecureBootStatus
	(*HardwareSecurityFeatures)(nil),      // 19: gpushield.integrity.v1.HardwareSecurityFeatures
	(*SecurityEvent)(nil),                 // 20: gpushield.integrity.v1.SecurityEvent
	(*IntegrityCheckRequest)(nil),         // 21: gpushield.integrity.v1.IntegrityCheckRequest
	(*IntegrityResponse)(nil),             // 22: gpushield.integrity.v1.IntegrityResponse
	(*GetIntegrityStatusRequest)(nil),     // 23: gpushield.integrity.v1.GetIntegrityStatusRequest
	(*IntegrityStatusResponse)(nil),       // 24: gpushield.integrity.v1.IntegrityStatusResponse
	(*UpdateTrustedBaselineRequest)(nil),  // 25: gpushield.integrity.v1.UpdateTrustedBaselineRequest
	(*UpdateTrustedBaselineResponse)(nil), // 26: gpushield.integrity.v1.UpdateTrustedBaselineResponse
	nil,                                   // 27: gpushield.integrity.v1.ComponentIntegrity.MetadataEntry
	nil,                                   // 28: gpushield.integrity.v1.SecurityEvent.DetailsEntry
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
}
var file_integrity_proto_depIdxs = []int32{
	29, // 0: gpushield.integrity.v1.IntegrityReport.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: gpushield.integrity.v1.IntegrityReport.overall_status:type_name -> gpushield.integrity.v1.IntegrityStatus
	5,  // 2: gpushield.integrity.v1.IntegrityReport.components:type_name -> gpushield.integrity.v1.ComponentIntegrity
	15, // 3: gpushield.integrity.v1.IntegrityReport.attestation:type_name -> gpushield.integrity.v1.AttestationData
	20, // 4: gpushield.integrity.v1.IntegrityReport.security_events:type_name -> gpushield.integrity.v1.SecurityEvent
	1,  // 5: gpushield.integrity.v1.ComponentIntegrity.component_type:type_name -> gpushield.integrity.v1.ComponentType
	0,  // 6: gpushield.integrity.v1.ComponentIntegrity.status:type_name -> gpushield.integrity.v1.IntegrityStatus
	6,  // 7: gpushield.integrity.v1.ComponentIntegrity.hash_measurements:type_name -> gpushield.integrity.v1.HashMeasurement
	7,  // 8: gpushield.integrity.v1.ComponentIntegrity.signature_verification:type_name -> gpushield.integrity.v1.SignatureVerification
	8,  // 9: gpushield.integrity.v1.ComponentIntegrity.runtime_integrity:type_name -> gpushield.integrity.v1.RuntimeIntegrity
	27, // 10: gpushield.integrity.v1.ComponentIntegrity.metadata:type_name -> gpushield.integrity.v1.ComponentIntegrity.MetadataEntry
	29, // 11: gpushield.integrity.v1.HashMeasurement.measured_at:type_name -> google.protobuf.Timestamp
	29, // 12: gpushield.integrity.v1.SignatureVerification.signature_timestamp:type_name -> google.protobuf.Timestamp
	9,  // 13: gpushield.integrity.v1.RuntimeIntegrity.memory_protection:type_name -> gpushield.integrity.v1.MemoryProtection
	11, // 14: gpushield.integrity.v1.RuntimeIntegrity.control_flow_integrity:type_name -> gpushield.integrity.v1.ControlFlowIntegrity
	13, // 15: gpushield.integrity.v1.RuntimeIntegrity.api_hooks:type_name -> gpushield.integrity.v1.APIHook
	14, // 16: gpushield.integrity.v1.RuntimeIntegrity.process_integrity:type_name -> gpushield.integrity.v1.ProcessIntegrity
	10, // 17: gpushield.integrity.v1.MemoryProtection.suspicious_regions:type_name -> gpushield.integrity.v1.MemoryRegion
	12, // 18: gpushield.integrity.v1.ControlFlowIntegrity.violations:type_name -> gpushield.integrity.v1.ControlFlowViolation
	29, // 19: gpushield.integrity.v1.ControlFlowViolation.detected_at:type_name -> google.protobuf.Timestamp
	16, // 20: gpushield.integrity.v1.AttestationData.tpm_attestation:type_name -> gpushield.integrity.v1.TPMAttestation
	18, // 21: gpushield.integrity.v1.AttestationData.secure_boot:type_name -> gpushield.integrity.v1.SecureBootStatus
	19, // 22: gpushield.integrity.v1.AttestationData.hardware_features:type_name -> gpushield.integrity.v1.HardwareSecurityFeatures
	17, // 23: gpushield.integrity.v1.TPMAttestation.pcr_measurements:type_name -> gpushield.integrity.v1.PCRMeasurement
	2,  // 24: gpushield.integrity.v1.SecurityEvent.event_type:type_name -> gpushield.integrity.v1.SecurityEventType
	3,  // 25: gpushield.integrity.v1.SecurityEvent.severity:type_name -> gpushield.integrity.v1.SecurityEventSeverity
	29, // 26: gpushield.integrity.v1.SecurityEvent.timestamp:type_name -> google.protobuf.Timestamp
	28, // 27: gpushield.integrity.v1.SecurityEvent.details:type_name -> gpushield.integrity.v1.SecurityEvent.DetailsEntry
	29, // 28: gpushield.integrity.v1.IntegrityResponse.processed_at:type_name -> google.protobuf.Timestamp
	0,  // 29: gpushield.integrity.v1.IntegrityStatusResponse.overall_status:type_name -> gpushield.integrity.v1.IntegrityStatus
	5,  // 30: gpushield.integrity.v1.IntegrityStatusResponse.components:type_name -> gpushield.integrity.v1.ComponentIntegrity
	29, // 31: gpushield.integrity.v1.IntegrityStatusResponse.last_check:type_name -> google.protobuf.Timestamp
	6,  // 32: gpushield.integrity.v1.UpdateTrustedBaselineRequest.trusted_hashes:type_name -> gpushield.integrity.v1.HashMeasurement
	7,  // 33: gpushield.integrity.v1.UpdateTrustedBaselineRequest.signature_requirements:type_name -> gpushield.integrity.v1.SignatureVerification
	29, // 34: gpushield.integrity.v1.UpdateTrustedBaselineResponse.updated_at:type_name -> google.protobuf.Timestamp
	21, // 35: gpushield.integrity.v1.IntegrityService.PerformIntegrityCheck:input_type -> gpushield.integrity.v1.IntegrityCheckRequest
	4,  // 36: gpushield.integrity.v1.IntegrityService.StreamIntegrityReports:input_type -> gpushield.integrity.v1.IntegrityReport
	23, // 37: gpushield.integrity.v1.IntegrityService.GetIntegrityStatus:input_type -> gpushield.integrity.v1.GetIntegrityStatusRequest
	25, // 38: gpushield.integrity.v1.IntegrityService.UpdateTrustedBaseline:input_type -> gpushield.integrity.v1.UpdateTrustedBaselineRequest
	4,  // 39: gpushield.integrity.v1.IntegrityService.PerformIntegrityCheck:output_type -> gpushield.integrity.v1.IntegrityReport
	22, // 40: gpushield.integrity.v1.IntegrityService.StreamIntegrityReports:output_type -> gpushield.integrity.v1.IntegrityResponse
	24, // 41: gpushield.integrity.v1.IntegrityService.GetIntegrityStatus:output_type -> gpushield.integrity.v1.IntegrityStatusResponse
	26, // 42: gpushield.integrity.v1.IntegrityService.UpdateTrustedBaseline:output_type -> gpushield.integrity.v1.UpdateTrustedBaselineResponse
	39, // [39:43] is the sub-list for method output_type
	35, // [35:39] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_integrity_proto_init() }
func file_integrity_proto_init() {
	if File_integrity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integrity_proto_rawDesc), len(file_integrity_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_integrity_proto_goTypes,
		DependencyIndexes: file_integrity_proto_depIdxs,
		EnumInfos:         file_integrity_proto_enumTypes,
		MessageInfos:      file_integrity_proto_msgTypes,
	}.Build()
	File_integrity_proto = out.File
	file_integrity_proto_goTypes = nil
	file_integrity_proto_depIdxs = nil
}
